/*
 FloorTiles v1.5 (https://github.com/tontsacom/floortiles)
 Copyright 2017
 Licensed under the MIT license
*/
(function(m){var q={tileSize:{x:200,y:150},tileLimit:{x:6,y:4},maxWidth:1E3,gap:3,minCol:2,maxCol:6,tag:"",animate:!0,animateTime:500,delayResizeTime:500,tiled:function(a,b){},debug:!1},n=function(a,b){this.$element=m(a);var d=this.$element.children();0==d.length&&m.error("No tiles in jQuery.floortiles");d.eq(0).data("tile")||m.error("The tile size of the element 0 in jQuery.floortiles is not specified");for(var f=d.get(0).tagName,e=1;e<d.length;e++)d.eq(e).data("tile")||m.error("The tile size of the element "+
e+" in jQuery.floortiles is not specified"),d.get(e).tagName!=f&&m.error("Not the same tags in tiles in jQuery.floor");d.css({position:"absolute"});this.$element.wrapInner('<div class="floortiles-wrapper" style="position:relative;max-width:100%;margin:0 auto;" />');m.extend(this,q);this.reset(b);this.$element.data("floortiles",this)};n.prototype.destructor=function(){this.$element.html(this.$element.children().html());this.$element.children().removeAttr("style")};n.prototype.reset=function(a){for(var b in a)if(b in
q)switch(b){case "tileSize":var d=this.minSize(a[b],"40x30");d||m.error("Wrong value "+a[b]+" of property "+b+" in jQuery.floortiles");this[b]=d;break;case "tileLimit":(d=getSize(a[b]))||m.error("Wrong value "+a[b]+" of property "+b+" in jQuery.floortiles");this[b]=d;break;default:this[b]=a[b]}else m.error("Undefined property "+b+" in jQuery.floortiles");this.refresh()};n.prototype.refresh=function(){this.width=Math.min(this.$element.width(),this.maxWidth);this.columns=Math.max(Math.min(Math.ceil((this.width+
this.gap)/this.tileSize.x),this.maxCol),this.minCol);var a=this.$element.find(".floortiles-wrapper").children(),b={tiles:[],order:[],order2:[],spaces:[],holes:[],poses:[]},d,f=0,e,c=0;for(this.tags=[];f<a.length;f++){if(d=a.eq(f).data("tag")){d=d.split(" ");var g=!1;""==this.tag&&(g=!0);for(e=0;e<d.length;e++)0>this.tags.indexOf(d[e])&&this.tags.push(d[e]),!g&&0<=this.tag.indexOf(d[e])&&(g=!0)}else g=!0;g?(d=this.minSizeTile(a.eq(f).data("tile")),b.tiles.push({x:d.x,y:d.y}),b.order.push(c++),b.order2.push(f),
b.poses.push({x:0,y:0,v:0,c:this.columns}),a.eq(f).css({display:"block"})):a.eq(f).css({display:"none"})}this.tags.sort();if(this.debug)var h=performance.now();f=this.assembly(b,this.columns,0,{i:0,y:0,v:0});this.debug&&console.log({iteration:f,time:performance.now()-h,state:b,floortiles:this});this.result(b)};n.prototype.result=function(a){for(var b=this.$element.find(".floortiles-wrapper"),d=b.children(),f=this.step(),e,c,g,h=0;h<a.tiles.length;h++)g=a.poses[h],e=this.boundSize(a.tiles[h]),c=this.boundSizeR(e,
g.c),g={x:f.x*g.x,y:f.y*g.v},c={x:f.x*c.x-this.gap,y:f.y*c.v-this.gap},this.tiled(d.eq(a.order2[h]),{index:a.order2[h],tile:e,pos:g,size:c,tileSize:this.tileSize}),this.$element.trigger("sited.floortiles",{el:d.eq(a.order2[h]),ui:{index:a.order2[h],tile:e,pos:g,size:c,tileSize:this.tileSize}}),this.animate&&this.$element.data("floortiles")?d.eq(a.order2[h]).animate({width:c.x+"px",height:c.y+"px",left:g.x+"px",top:g.y+"px"},this.animateTime):d.eq(a.order2[h]).css({width:c.x+"px",height:c.y+"px",left:g.x+
"px",top:g.y+"px"});b.css({width:f.x*this.columns-this.gap+"px",height:f.y*this.maxSpacesV(a,0,this.columns)-this.gap+"px"})};n.prototype.assembly=function(a,b,d,f){var e=[],c=[],g=0,h,p,m;this.sitAll(a,b,f);var n=a.holes.length;var r=this.maxSpaces(a,0,b)-this.minSpaces(a,0,b);e.push({order:a.order.join(),mode:0,holes:n,height:this.maxSpacesV(a,0,b),tear:r,chaos:this.chaos(a)});for(c=0;700>d++;){if(0<n){var k=a.order.findIndex(function(b){return b==a.holes[0].i});switch(g){case 0:for(h=1;h<n&&a.holes[h].x==
a.holes[0].x+h&&a.holes[h].y==a.holes[0].y;h++);for(;a.holes[0].x+h<b&&!(a.spaces[a.holes[0].x+h].y>a.holes[0].y);h++);var l=k+1;for(m=p=0;l<a.order.length&&!(a.poses[a.order[l]].y>=a.poses[a.order[k]].y&&a.tiles[a.order[l]].x==h);l++)a.poses[a.order[l]].y>=a.poses[a.order[k]].y&&a.tiles[a.order[l]].x<h&&a.tiles[a.order[l]].x>p&&(p=a.tiles[a.order[l]].x,m=l);l>=a.order.length&&(l=m);if(0<l){h=a.tiles[a.order[l]].x;c=a.order.slice(k,l+1).sort(function(b,c){return a.tiles[b].x==h&&a.tiles[c].x==h||
a.tiles[b].x!=h&&a.tiles[c].x!=h?b-c:a.tiles[b].x==h?-1:1});for(h=c.length;h--;)a.order[k+h]=c[h];c.length=0}else for(h=this.tileReshuffle(a,f);k-- >f.i&&(a.tiles[a.order[k]].x!=a.tiles[a.order[k+1]].x&&a.order.splice(k,0,a.order.splice(k+1,1)[0]),a.order[k]!=h&&a.order[k+1]!=h););break;case 1:for(p=0;k-- >f.i;)if(2==a.tiles[a.order[k]].y&&1==a.tiles[a.order[k]].x)p=1,h=k;else if(1==a.tiles[a.order[k]].y&&1==a.tiles[a.order[k]].x&&1==p){p=2;l=k;break}2==p&&a.order.splice(l,0,a.order.splice(h,1)[0])}}else{if(2>
r)break;k=this.maxSpaces(a,0,b);h=a.spaces.findIndex(function(a){return a.y==k});for(k=a.order.length;k-- >f.i&&(a.poses[a.order[k]].x!=h||a.poses[a.order[k]].y+a.tiles[a.order[k]].y!=a.spaces[h].y););switch(g){case 0:case 1:case 2:switch(g){case 0:for(l=k;l-- >f.i&&!(a.tiles[a.order[l]].y<a.tiles[a.order[k]].y&&a.tiles[a.order[l]].x>a.tiles[a.order[k]].x););if(l>=f.i)break;e[c].mode++;case 1:for(l=k;l-- >f.i&&!(a.tiles[a.order[l]].y<a.tiles[a.order[k]].y&&a.tiles[a.order[l]].x==a.tiles[a.order[k]].x););
if(l>=f.i)break;e[c].mode++;case 2:for(l=f.i;l<k&&(a.tiles[a.order[l]].y==a.tiles[a.order[k]].y||a.tiles[a.order[l]].x==a.tiles[a.order[k]].x);l++);l<k||e[c].mode++}if(l>=f.i&&l<k){for(h=l;l++&&(a.tiles[a.order[l]].y!=a.tiles[a.order[k]].y||a.tiles[a.order[l]].x!=a.tiles[a.order[k]].x););a.order.splice(h,0,a.order.splice(l,1)[0]);break}case 3:for(p=0;k-- >f.i;)if(2==a.tiles[a.order[k]].y&&1==a.tiles[a.order[k]].x)p=1,h=k;else if(1==a.tiles[a.order[k]].y&&1==a.tiles[a.order[k]].x&&1==p){p=2;l=k;break}2==
p&&a.order.splice(l,0,a.order.splice(h,1)[0])}}this.sitAll(a,b,f);m=a.order.join();p=e.findIndex(function(a){return a.order==m});if(0<=p){c=e.slice(0).sort(function(a,b){return a.holes!=b.holes?a.holes-b.holes:a.tear-b.tear});1<c.length&&(c.length=1);c.sort(function(a,b){return a.holes!=b.holes?a.holes-b.holes:a.mode-b.mode});if(0==c[0].holes&&3<c[0].mode||0<c[0].holes&&1<c[0].mode){c.length=0;break}m=c[0].order;p=e.findIndex(function(a){return a.order==m});c.length=0;g=++e[p].mode;n=e[p].holes;r=
e[p].tear;c=p;d--;this.splitOrder(a,e[p].order);this.sitAll(a,b,f);if(0==n&&2>r)break}else n=a.holes.length,r=this.maxSpaces(a,0,b)-this.minSpaces(a,0,b),e.push({order:m,mode:0,holes:n,height:this.maxSpacesV(a,0,b),tear:r,chaos:this.chaos(a)}),g=0,c=e.length-1}if(!this.debug||700>d)e.sort(function(a,b){return a.holes!=b.holes?a.holes-b.holes:a.height!=b.height?a.height-b.height:a.tear!=b.tear?a.tear-b.tear:a.chaos-b.chaos}),this.splitOrder(a,e[0].order),this.sitAll(a,b,f),n=a.holes.length;if(0<n&&
700>d){k=this.tileReshuffle(a,f);h=a.order.findIndex(function(a){return a==k});c=a.order.slice(h).sort(function(a,b){return a-b});for(l=c.length;l--;)a.order[h+l]=c[l];this.sitAll(a,b,f);return this.assembly(a,b-1,d,{i:h,y:a.poses[a.order[h]].y,v:a.poses[a.order[h]].v})}return d};n.prototype.tileReshuffle=function(a,b){for(var d=a.order.findIndex(function(b){return b==a.holes[0].i}),f=[],e=a.holes[0].y,c=b.i;c<d;c++)f.push({i:a.order[c],y:a.poses[a.order[c]].y,y2:a.poses[a.order[c]].y+a.tiles[a.order[c]].y});
for(d=f.filter(function(a){return a.y<=e&&a.y2>e}).sort(this.compareH);d[0].y<e;)e=d[0].y,d=f.filter(function(a){return a.y<=e&&a.y2>e}).sort(this.compareH);return d[0].i};n.prototype.sitAll=function(a,b,d){for(var f=0;f<b;f++)a.spaces[f]={y:d.y,v:d.v};a.holes.length=0;for(f=d.i;f<a.order.length;f++)a.poses[a.order[f]]=this.sit(a.tiles[a.order[f]],a,b,a.order[f])};n.prototype.sit=function(a,b,d,f){a=this.boundSize(a);if(a.x>=d){a=this.boundSizeR(a,d);var e={x:0,y:this.maxSpaces(b,0,d),v:this.maxSpacesV(b,
0,d),c:d};for(var c=0;c<d;c++){for(var g=b.spaces[c].y;g<e.y;g++)b.holes.push({x:c,y:g,v:g-b.spaces[c].y+b.spaces[c].v,i:f});b.spaces[c]={y:e.y+a.y,v:e.v+a.v}}b.holes.sort(this.compareH);return e}a=this.boundSizeR(a,d);var h=[];for(c=0;c<d-a.x+1;c++)h[c]={x:c,y:this.maxSpaces(b,c,c+a.x),v:this.maxSpacesV(b,c,c+a.x)};h.sort(this.compareH);e=[];for(c=0;c<b.holes.length;c++){var m=b.holes[c];for(g=1;g<a.x&&(!(c+g>=b.holes.length||b.holes[c+g].x!=m.x+g||b.holes[c+g].y!=m.y)||!(b.holes[c].x+g>=d||b.spaces[b.holes[c].x+
g].y>m.y));g++);g==a.x&&e.push(m)}var n=e.length;if(0<n&&1<a.y){e.sort(this.compareV);for(c=0;c<n-a.y+1;c++){m=e[c];for(g=1;g<a.y&&e[c+g].x==m.x&&e[c+g].y==m.y+g;g++);g==a.y&&e.push(m)}e.splice(0,n);e.sort(this.compareH)}if(0<e.length&&0>this.compareH(e[0],h[0])){e={x:e[0].x,y:e[0].y,v:e[0].v,c:d};for(c=0;c<b.holes.length&&(b.holes[c].x!=e.x||b.holes[c].y!=e.y);c++);for(g=1;g<a.x&&c+g<b.holes.length&&b.holes[c+g].x==e.x+g&&b.holes[c+g].y==e.y;g++);for(b.holes.splice(c,g).forEach(function(a){b.holes.forEach(function(b){b.i==
a.i&&b.x==a.x&&b.y<a.y&&(b.i=f)})});g<a.x;g++){for(d=b.spaces[e.x+g].y;d<e.y;d++)b.holes.push({x:e.x+g,y:d,v:d-b.spaces[e.x+g].y+b.spaces[e.x+g].v,i:f});b.spaces[e.x+g]={x:e.x+g,y:e.y+a.y,v:e.v+a.v}}for(d=1;d<a.y;d++){for(;c<b.holes.length&&(b.holes[c].x!=e.x||b.holes[c].y!=e.y+d);c++);for(g=1;g<a.x&&c+g<b.holes.length&&b.holes[c+g].x==e.x+g&&b.holes[c+g].y==e.y+d;g++);b.holes.splice(c,g)}b.holes.sort(this.compareH);return e}e={x:h[0].x,y:h[0].y,v:h[0].v,c:d};for(c=e.x;c<e.x+a.x;c++){for(g=b.spaces[c].y;g<
e.y;g++)b.holes.push({x:c,y:g,v:g+b.spaces[c].v-b.spaces[c].y,i:f});b.spaces[c]={y:e.y+a.y,v:e.v+a.v}}b.holes.sort(this.compareH);h.length=0;return e};n.prototype.compareH=function(a,b){return a.y!=b.y?a.y-b.y:a.x-b.x};n.prototype.compareV=function(a,b){return a.x!=b.x?a.x-b.x:a.y-b.y};n.prototype.step=function(){var a=Math.min(Math.round((this.width+this.gap)/this.columns-this.gap),this.tileSize.x);return{x:a+this.gap,y:Math.round(a/this.tileSize.x*this.tileSize.y)+this.gap}};n.prototype.minSize=
function(a,b){var d=getSize(a),f=getSize(b);return d?{x:Math.max(d.x,f.x),y:Math.max(d.y,f.y)}:!1};n.prototype.minSizeTile=function(a){return(a=this.minSize(a,"1x1"))?a:{x:1,y:1}};n.prototype.boundSize=function(a){return{x:Math.min(a.x,this.tileLimit.x),y:Math.min(a.y,this.tileLimit.y)}};n.prototype.boundSizeR=function(a,b){return a.x>b?{x:b,y:1,v:a.y/a.x*b}:a.x==b?{x:b,y:1,v:a.y}:{x:a.x,y:a.y,v:a.y}};n.prototype.minSpaces=function(a,b,d){var f=a.spaces[b].y;for(b+=1;b<d;b++)f=Math.min(f,a.spaces[b].y);
return f};n.prototype.maxSpaces=function(a,b,d){var f=a.spaces[b].y;for(b+=1;b<d;b++)f=Math.max(f,a.spaces[b].y);return f};n.prototype.maxSpacesV=function(a,b,d){var f=a.spaces[b].v;for(b+=1;b<d;b++)f=Math.max(f,a.spaces[b].v);return f};n.prototype.chaos=function(a){for(var b=0,d=0;b<a.order.length;b++)d+=Math.pow(b-a.order[b],2);return d};n.prototype.splitOrder=function(a,b){for(var d=b.split(","),f=d.length;f--;)a.order[f]=parseInt(d[f])};var t={init:function(a){return this.each(function(){var b=
m(this).data("floortiles"),d;b?b.reset(a):(b=new n(this,a),m(window).on("resize.floortiles",function(){d&&clearTimeout(d);d=setTimeout(function(){b.refresh()},b.delayResizeTime)}))})},refresh:function(){return this.each(function(){m(this).data("floortiles").refresh()})},gettags:function(){return m(this.eq(0)).data("floortiles").tags},destroy:function(){return this.each(function(){m(window).off(".floortiles");m(this).data("floortiles").destructor();m(this).removeData("floortiles")})}};m.fn.floortiles=
function(a){if(t[a])return t[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)m.error("The method named "+a+" does not exist in jQuery.floortiles");else return t.init.apply(this,arguments)}})(jQuery);function getSize(m){var q=m.split("x");if(2!=q.length)return!1;m=parseInt(q[0]);q=parseInt(q[1]);return 1>m||1>q?!1:{x:m,y:q}};